name: "Publish on Dockerhub"
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      
      - name: Publish
        uses: dinushchathurya/build-tag-push-action@v1.2.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: .
          file: docker/Dockerfile
          repoOwner: ${{ secrets.DOCKER_USERNAME }}
          repository:  multiplicator
          tag: ${{ steps.vars.outputs.tag }}
          
